##
#
# Travis CI script for keyvi
#


language: cpp

compiler:
# disable, does not build with current msgpack - clang
  - gcc

python:
  - 2.7

sudo: required

services:
  - docker

env:
  matrix:
    - BUILD_TYPE=linux      CONF=debug    ARCH=x86_64
    - BUILD_TYPE=linux      CONF=release  ARCH=x86_64
    - BUILD_TYPE=linux      CONF=coverage ARCH=x86_64
    - BUILD_TYPE=manylinux  DOCKER_IMAGE=cliqz/keyvi-manylinux-builder
    - BUILD_TYPE=sdist
  global:
    - GITHUB_REPO='cliqz-oss/keyvi'
    - secure: "cy3LYIeuSxIdDt4GArpStoawmlEXy7oVX/Z72hwcXVj6EgQ8za16GaayQCLbHy9Hlm0K42QmWg4s7iOm/QzKBlZAwvHMktmHIVoovXe+i83bRVclMr/zvzhEeSyCy4xbBEBT8qt4p0dwX4hOF6cfy+rpNsI+CMBbGgMSS/MZHm/FmF5fKqcZBJfZfEPOqOukID4NPirDlZ8Jmg8JR1K722+xXvwbSif0a6wJ3p517JjYJxO8a7AzdXJMXC3sJmpsSCBwp+NG9BrwJ/MgQFHKUEhPoPFOEI7P57rH9Cax8+y9j7ukwlB36Ae5ApddcXYbQMOtpoA+DvR5JbsbYWi4/T6qUntYmpRy5gPVD/IwIAldEt3iERswjWFHgUjN+JaJ6YqQHl5ks++NZbB6W8eqP2Id1Oa669b6uxFn62Ln43TcvY4bapJEscj7goReiQGjwIWjBxphP/eJaPae642HnpBijPjAG+uA8IyO2nuY/+xULMiNXDFGVmBC5VfYp95Y71ZlUpfUv6u96mXc3ruWmDRzGNNgNXmzIGfD5bxn2uxMykOW6ubG4mnxOT/qMia8yrYsPYdBsvc1u2XWHAUUrHPVr9HmFo68y3AfuXwXH2Eb0fGTxNmaihabcqoBdm6HRK3aRLqXweBI2xXyOY8Tf07hUy+G7qkg2ZrsEgwWg+k="  # COVERALLS_REPO_TOKEN
    - secure: "ERiIKQRkktXO6W8Z6khwHe577q4LHT5L5MptcEux6pDWGfAVYnJkYpeCmMPaBOLnzYAGVBLuHfW9RkfFB1rGhzUT71jB5CSOIjozVVuZ2PlUJTAS2VfSYyON8OiQ4jyV/elqMIOlJh001y221nlvuZcZXjdJcuH6WeO8ehpA5f0tmLuqlyutQzYN1JCiHy/YbCRVHUzfqH7Wgjn/Y/XDgrwEG0sgygi4GKokzSVUZWT7YnXo/TCV1y2HLPrzZftwq/KOEtDqglCRK3HLVxnSJ9SoLDBjmAHpyOHlcnCtsRai31p45VAfwPsM6/gE3HZ0EI4jaWhV24u1cUOeruT5MpBpFP0gMiDF6lVWycljUhIAPsqi2cmhc008XHv7l1yo1ehBZvbjFGcmML6CA8X8uJviOH4Vl2onLuG4clPCYzIrVpTNGXCJt8gL7eov21DslEmKXyoItBaEAub5VVzPv7yU/lF4cvndedCDo9uYzfcWWShk2VGAACUEvp6lKb8A5H+2aO3cQebcoRW93pK5wDqo47Gcf2ZM6C2JHrIg4PJg10sVauDnwYVMSwOn3Cb6nLjpm+bZcPIVdZ+kRSfre8PjfJmxFKQf/wg1qAjaoyt+NicZ1OLSTTHZmOuNxNz5nDActgQ973wmb7Zji8oUja9gkBCpDBqiPONNCx3NnAA="  # PYPI USERNAME
    - secure: "FO0lmPJ0MHC+cf3k9ZiOAn154nvLoXVS2lMRMc/KHjgAL82prZ+qBlvDrKMfWDvyv0TXiwX65qBb+Y+5rrbFalYY24iL3IKYoenoewXahulaD1yPR+KzYqezRsyKqSlg2x8kjRkZz95XZkYA7yiL7NO7hDrs79mZYh6oGGU7XxnkVoJ2jVRmWaaaXfbGbix/kK/jdevidKX9WpFzs/XxfqOlEL5mTMv/Hsc6Bp83+zT1MlF3+ed4j5lcFtmLHexKdJ8NXOxpnzMY73r8xKWuidv2uxmc3qwbC457lIB97rU4UuA5tJNhcFDu2s/Gwca+oHnNMQRfDq08Gt35mR9JYSoVE5QJ9e6wTtxGPISULH0LzL5RRGFKw/D7IvCofIbU3biy4KT/infjiUT+pPX7YV6/Oczh0gEtPT4awP3+18RDBMHnU1437nNyQJMG/CXUi7FNkrhN+zNxKO2/rYDoIOGUCDr9sSZrsAdpfXuogKzbaepzZtdGKqEPc3qn47pxr7nJyzyMAEgr7rZsHg6uqpYuaJg8BpCCgW5SB1gi4+outsm8yaGnGLn3iLuKk6HAaEqUTUGUgkwZC9f2WIixlaEWtgwhcAJyxU2XDrwT+UoIz4+4DNYqltbDP9YHkLu0qU31z9G/WiJN1l+iLonLdqDL2toUlDUNcOWZ+wDb+2U="  # PYPI_PASSWORD

before_install:
  - pip install --upgrade pip
  - pip install --user twine
  - pip install --user --use-wheel --install-option="--no-cython-compile" cython
  - pip install --user --use-wheel pytest
  - pip install --user --use-wheel msgpack-python
  - if [ "$CC" = "gcc" ] && [ "$CONF" = "coverage" ]; then pip install --user --use-wheel coveralls-merge; fi
  - if [ "$CC" = "gcc" ] && [ "$CONF" = "coverage" ]; then pip install --user --use-wheel cpp-coveralls; fi

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$DOCKER_IMAGE" != "" ]; then docker pull $DOCKER_IMAGE ; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
# disable, LLVM broken for now    - llvm-toolchain-precise-3.6
    - boost-latest
    packages:
    - gcc-4.8
    - g++-4.8
# disabled due to https://github.com/travis-ci/travis-ci/issues/6120    - clang
    - scons
    - valgrind
    - cmake
    - libboost-thread1.55-dev
    - libboost-system1.55-dev
    - libboost-test1.55-dev
    - libboost1.55-dev
    - libboost-date-time1.55-dev
    - libboost-regex1.55-dev
    - libboost-filesystem1.55-dev
    - libboost-program-options1.55-dev
    - libboost-iostreams1.55-dev
    - libsnappy-dev
    - zlib1g-dev
    - doxygen
    - libstdc++-4.8-dev

script:
  - if [ "$BUILD_TYPE" == "linux" ]; then ./travis/build_linux.sh ; fi
  - if [ "$BUILD_TYPE" == "manylinux" ]; then ./travis/build_manylinux_package.sh ; fi
  - if [ "$BUILD_TYPE" == "sdist" ]; then ./travis/build_sdist_package.sh ; fi

after_success:
  - if [ "$CC" = "gcc-4.8" ] && [ "$CONF" = "coverage" ]; then ./travis/coverage.sh ; fi

deploy:
  provider: script
  script: travis/upload_packages.sh
  skip_cleanup: true
  on:
    tags: true
